### ISSUE TITLE
Avoid `env` file baked into an image

### ISSUE THREAD

**Issue by dsha256** [dsha256/plfa#35]

**Comment by dsha256** [comment]
Thanks, @ABGEO! Currently, I'm using [viper](https://github.com/spf13/viper). I mean that the ENV vars should be changed during the runtime and this ganna be happened completely randomly by the admin tool or maybe from any of the cloud provider's secret management tools. This depends on the decision we'll make and develop. Personally, I'd prefer a cloud-agnostic approach which should be the admin UI developed by me or probably someone from the community. I'd love to go with a highly flexible solution while preferring to minimize third-party dependencies.

**Comment by ABGEO** [comment]
@dsha256 you can use viper's  `AutomaticEnv()` method and pass the values via ENV variables on runtime. e.g for docker it would be:

```yaml
version: "3"
services:
  app:
    image: dsha256/plfa
    environment:
        PRAGMATIC_FEED_WS_URL: "The vendor WS URL"
        CASINO_ID: "Casino's ID"
        TABLE_IDS: "Comma-seperated tables IDs"
        CURRENCY_IDS: "Comma-seperated Currency IDs"
        REDIS_PORT: "Port to run and connect to Redis DB"
        SERVER_PORT: "Port to run the HTTP server on"
        PUSHER_CHANNEL_ID: "Pusher.com's channel ID"
        PUSHER_PERIOD_MINUTES: "Period to push data into the pusher channel"
        PUSHER_APP_ID: "Pusher.com's app ID"
        PUSHER_KEY: "Pusher.com's app key"
        PUSHER_SECRET: "Pusher.com's app secret"
        PUSHER_CLUSTER: "Pusher.com's app cluster"
```

It would by same for other orchestrators like k8s
